#!/usr/bin/python3

from math import pi 

def MultArea(r):
	return pi*(r**2)

radii = [12, 23, 4, 8, True, "namnny"]

message = "circle with radius r = {radius} and area is ={area} "

for r in radii :
	A = MultArea(r)
	print(message.format(radius=r, area=A))





